### ISSUE TITLE
Add support for React 17 + enzyme-adapter-react-17

### ISSUE THREAD

**Issue by alexandr-g** [alexandr-g/cra-template-typescript-redux#132]
Enzyme doesn't support React 17 yet enzymejs/enzyme#2429, need to wait for `enzyme-adapter-react-17` to be able to run tests without errors.

https://github.com/enzymejs/enzyme/issues/2462#issuecomment-716180665

![Screen Shot 2020-11-18 at 9 03 38 AM](https://user-images.githubusercontent.com/9251327/99502237-141c9380-297d-11eb-8a6e-9e655b841289.png)

**Comment by tonoslav** [comment]
> Enzyme doesn't support React 17 yet [enzymejs/enzyme#2429](https://github.com/enzymejs/enzyme/issues/2429), need to wait for `enzyme-adapter-react-17` to be able to run tests without errors.
> 
> [enzymejs/enzyme#2462 (comment)](https://github.com/enzymejs/enzyme/issues/2462#issuecomment-716180665)
> 
> ![Screen Shot 2020-11-18 at 9 03 38 AM](https://user-images.githubusercontent.com/9251327/99502237-141c9380-297d-11eb-8a6e-9e655b841289.png)

any workaround ? without returning to react 16 ?

**Comment by tonoslav** [comment]
This might help somebody
https://github.com/wojtekmaj/enzyme-adapter-react-17
