### ISSUE TITLE
Warning: React does not recognize the `computedMatch` prop on a DOM element.

### ISSUE THREAD

**Issue by TroyJoachim** [alexandr-g/cra-template-typescript-redux#58]
Warning: React does not recognize the `computedMatch` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `computedmatch` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (at App.tsx:13)
    in Switch (at App.tsx:12)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.tsx:10)
    in App (at src/index.tsx:12)
    in Provider (at src/index.tsx:11)

Browser: Google Chrome/Microsoft Edge

According to the documentation: https://reacttraining.com/react-router/web/api/Switch

`All children of a <Switch> should be <Route> or <Redirect> elements. Only the first child to match the current location will be rendered.`

It looks like you have a div inside the switch statement.

**Comment by alexandr-g** [comment]
Hey @TroyJoachim,

Thanks for pointing out and issue description/help. The issue should be fixed with a new release 🙂 👍
